apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-project
  template:
    metadata:
      labels:
        app: mini-project
    spec:
      containers:
      - name: mini-project
        image: thowfiqismail/mini-project-app:latest
        ports:
        - containerPort: 80
